hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 4096
  train_batch_size: 256
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang_async
    multi_turn:
      enable: True
      max_turns: 5
      tool_kwargs:
        tool_config_path: "./config/tool_config/code_exec_tool_config.yaml"
